### ISSUE TITLE
Blog broken

### ISSUE THREAD

**Issue by mfeurer** [openml/blog#36]
I just had a look at the blog and it turns out to be broken. The overview page doesn't render properly and the links to the individual articles do not work.

**Comment by joaquinvanschoren** [comment]
Where are you looking?

The blog is here: http://blog.openml.org/

**Comment by mfeurer** [comment]
At https://openml.github.io/blog/ as mentioned in the docs. So the docs are wrong then I guess?

**Comment by joaquinvanschoren** [comment]
Yes, I updated the docs. Thanks!
